name: do-app-pf-nodejs
region: sfo
project_id: 021c4da8-a273-4360-b068-f1fd1a03b3d2

services:
  - name: web
    github:
      repo: polymath-pat/do-app_pf-nodejs
      branch: main
      deploy_on_push: true

    run_command: npm start

    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: DATABASE_CA_CERT
        scope: RUN_TIME
        value: ${db.CA_CERT}

    instance_count: 1
    instance_size_slug: basic-xxs

databases:
  - name: db
    engine: PG
    production: true
    cluster_name: db-postgresql-sfo3-93898
